import 'package:fitsole_flutter/data/env/env.dart';
import 'package:fitsole_flutter/domain/blocs/blocs.dart';
import 'package:fitsole_flutter/presentation/helpers/helpers.dart';
import 'package:fitsole_flutter/presentation/screen/home/home.dart';
import 'package:fitsole_flutter/presentation/screen/home/home.dart';
import 'package:fitsole_flutter/presentation/themes/colors_frave.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:google_nav_bar/google_nav_bar.dart';

part 'bottom_navbar.dart';
part 'text_fitsole.dart';
part 'btn_fitsole.dart';
part 'text_field_fitsole.dart';
part 'custom_app_bar.dart';
part 'search_bar.dart';
